  # IP information for network adapter
  FixServer: 127.0.0.1
  FixPort: 3490

  # nodeID, currently only used in touchscreen buttons
  # the value will replace {id} in the button's dbkey
  nodeID: 1

  # Menu timeout in ms
  # All this does is set fix key MENUITEM to True after a timeout
  # Individual buttons need to have conditions that will show/hide the button
  # based on the value of MENUITEM
  # The main buttons included by default have such logic
  # Uncomment the next line to enable this feature:
  #button_timeout: 10000 

  # Screen Geometry
  # Defaults to screen size if screenWidth or screenHeight is not defined
  screenWidth: 1280
  screenHeight: 720
  #screenWidth: 1024
  #screenHeight: 768
  #screenWidth: 1920
  #screenHeight: 1080

  # Set EFIS to occupy the entire screen without system border / menu
  screenFullSize: False

  # Screen background color RGB
  screenColor: (0,0,0)

  # If left out the first defined screen will be default
  defaultScreen: PFD


