type: simple
text: ""
dbkey: TSBTN{id}13
conditions:
  - when: "SCREEN eq 'ANDROID'"
    actions:
      - set text: PFD
      - set bg color: lightgray
    continue: true
  - when: "SCREEN ne 'ANDROID'"
    actions:
      - set text: ANDROID
      - set bg color: lightgray
    continue: true
  - when: "CLICKED eq true and [ SCREEN ne 'ANDROID' ]" 
    actions:
      - show screen: ANDROID
  - when: "CLICKED eq true and SCREEN eq 'ANDROID'"
    actions:
      - show screen: PFD

