instruments:
  - type: virtual_vfr
    row: 0
    column: 0
    span:
      rows: 110
      columns: 155
    options: 
      font_percent: 0.025
  - type: horizontal_situation_indicator
    disabled: HSI
    row: 0
    column: 0
    span:
      rows: 110
      columns: 155
    move:
      shrink: 12
    options:
      #fontSize: 48
      font_percent: 0.05
      #fg_color: "#aaaaaa"
      bg_color: "#aaaaaa"
      cdi_enabled: true
      gsi_enabled: true
  - type: altimeter_tape
    row: 0
    column: 140
    span:
      rows: 110
      columns: 15
    options:
      #fontsize: 28
      font_percent: 0.24
      #number_font_size: 40
      altitude: true
  - type: vsi_pfd
    disabled: VSI_BALL
    row: 0
    column: 130
    span:
      rows: 50
      columns: 10
  - type: numeric_display
    disabled: VSI_BALL
    row: 50
    column: 128.5
    span:
      rows: 5
      columns: 12
    options:
      font_mask: "0000"
      decimal_places: 0
      dbkey: VS
  - type: altimeter_tape
    disabled: VSI_TAPE
    row: 30
    column: 127
    span:
      rows: 50
      columns: 13
    options:
      dbkey: VS
      font_mask: "00000"
      total_decimals: 5
      altitude: true
      majorDiv: 100
      minorDiv: 50
  - type: static_text
    disabled: VSI_TAPE
    row: 49.4
    column: 129.8
    span:
      rows: 2.2
      columns: 3
    options:
      text: VSI
      font_mask: VSI
  - type: airspeed_tape
    row: 5
    column: 0
    span:
      rows: 100
      columns: 15
    options:
      font_percent: 0.25
  - type: include,includes/vertical_dimmer_control.yaml
    row: 90
    column: 16
    span:
      rows: 20
      columns: 6
  - type: heading_display
    disabled: HEADING
    row: 0
    column: 72.5
    span:
      rows: 7
      columns: 10
    options:
      bg_color: "#00000000"
      fg_color: "#FFFFFF"
      #fontSize: 5 #47
      #font_percent: 0.65
  - type: static_text
    disabled: AUTO_PILOT
    row: 0
    column: 0
    span:
      rows: 5
      columns: 22
    options:
      text: "Auto Pilot:"
      alignment: AlignRight
      font_mask: "Auto_Pilot:"
  - type: value_text
    disabled: UTC_TIME
    row: 0
    column: 97
    span:
      rows: 5
      columns: 35
    options:
      dbkey: TIMEZ
      font_mask: "HH:MM:SS ZZZ"
      #fontName: DSEG14 Modern Mini, Bold
  - type: value_text
    disabled: LOCAL_TIME
    row: 5
    column: 97
    span:
      rows: 5
      columns: 35
    options:
      dbkey: TIMEL
      font_mask: "HH:MM:SS ZZZ"
  - type: value_text
    disabled: AUTO_PILOT
    row: 0
    column: 23
    span:
      rows: 5
      columns: 50
    options:
      dbkey: MAVMSG
      font_mask: "12345678901234567890"
  - type: static_text
    disabled: BARO_CONTROLS
    row: 90
    column: 118
    span:
      rows: 4
      columns: 10
    options:
      text: "Baro:"
      font_mask: "Baro:"
      alignment: AlignRight
  - type: numeric_display
    disabled: BARO_CONTROLS
    row: 90
    column: 129
    span:
      rows: 4
      columns: 12
    options:
      font_mask: "00.00"
      dbkey: BARO
      decimal_places: 2
      pressure: true
  - type: button
    disabled: BARO_CONTROLS
    row: 83
    column: 118
    span:
      rows: 7
      columns: 10
    options:
      config: buttons/baro-down-invisible.yaml
  - type: button
    disabled: BARO_CONTROLS
    row: 83
    column: 129
    span:
      rows: 7
      columns: 10
    options:
      config: buttons/baro-up-invisible.yaml
  - type: static_text
    disabled: PRESSURE_DISPLAY
    row: 95
    column: 118
    span:
      rows: 4
      columns: 10
    options:
      text: "DALT:"
      font_mask: "DALT:"
      alignment: AlignRight
  - type: numeric_display
    disabled: PRESSURE_DISPLAY
    row: 95
    column: 129
    span:
      rows: 4
      columns: 15
    options:
      font_mask: "10000"
      dbkey: DALT
      decimal_places: 0
      altitude: true
  - type: static_text
    disabled: PRESSURE_DISPLAY
    row: 100
    column: 118
    span:
      rows: 4
      columns: 10
    options:
      text: "PALT:"
      font_mask: "PALT:"
      alignment: AlignRight
  - type: numeric_display
    disabled: PRESSURE_DISPLAY
    row: 100
    column: 129
    span:
      rows: 4
      columns: 15
    options:
      font_mask: "10000"
      dbkey: PALT
      decimal_places: 0
      altitude: true
  - type: static_text
    disabled: PRESSURE_DISPLAY
    row: 105
    column: 118
    span:
      rows: 4
      columns: 10
    options:
      text: "OAT:"
      font_mask: "OAT:"
      alignment: AlignRight
  - type: numeric_display
    disabled: PRESSURE_DISPLAY
    row: 105
    column: 129
    span:
      rows: 4
      columns: 10
    options:
      font_mask: "100"
      units_font_mask: "oF"
      dbkey: OAT
      temperature: true
      show_units: true
      decimal_places: 0
      #show_value: false
  - type: include,includes/trim/pitch-yaw-roll-combined.yaml
    disabled: TRIM_CONTROLS
    row: 77
    column: 13
    span:
      rows: 30
      columns: 43
  - type: button
    disabled: LEADER_INDICATOR
    row: 0
    column: 150
    span:
      rows: 5
      columns: 5
    options:
      config: buttons/leader.yaml
  - type: value_text
    disabled: AIRCRAFT_IDENTIFIER
    row: 104
    column: 70
    span:
      rows: 6
      columns: 16
    options:
      dbkey: ACID 
      font_mask: NXXXXX
  - type: static_text
    disabled: VERSION_DISPLAY
    row: 105
    column: 0
    span:
      rows: 2.5
      columns: 9
    options:
      text: "pyefis:"
      font_mask: "pyefis:"
      alignment: AlignRight
  - type: value_text
    disabled: VERSION_DISPLAY
    row: 105
    column: 9
    span:
      rows: 2.5
      columns: 9
    options:
      dbkey: PYEFIS_VERSION
      font_mask: X.X.XX
  - type: static_text
    disabled: VERSION_DISPLAY
    row: 107
    column: 0
    span:
      rows: 2.5
      columns: 9
    options:
      text: "gateway:"
      font_mask: "gateway:"
      alignment: AlignRight
  - type: value_text
    disabled: VERSION_DISPLAY
    row: 107
    column: 9
    span:
      rows: 2.5
      columns: 9
    options:
      dbkey: GATEWAY_VERSION
      font_mask: X.X.XX



