instruments:
  - type: ganged_vertical_bar_gauge
    gang_type: horizontal
    ratio: 0.2
    row: 0
    column: 0
    span:
      rows: 40
      columns: 45
    groups:
      - name: FUEL
        gap: 0 
        common_options:
          showUnits: true
          smallFontPercent: 0.060
          bigFontPercent: 0.085
          bar_width_percent: 0.5
          lineWidthPercent: 0.7
          textGap: 8
        instruments:
          -
            options:
              name: "Fuel"
              decimalPlaces: 0
              dbkey: FUELP1
          -   
            options:
              name: "Flow"
              decimalPlaces: 1
              dbkey: FUELF1
          - 
            options:
              name: "Total"
              decimalPlaces: 0
              dbkey: FUELQT
          -
            options:
              name: "Left"
              decimalPlaces: 1
              dbkey: FUELQ1
          -
            options:
              name: "Center"
              decimalPlaces: 1
              dbkey: FUELQ2
          -
            options:
              name: "Right"
              decimalPlaces: 1
              dbkey: FUELQ3
