main:
  # IP information for network adapter
  FixServer: 127.0.0.1
  FixPort: 3490
  # Screen Geometry
  #screenWidth: 1024
  #screenHeight: 768
  screenWidth: 800
  screenHeight: 480

  # Set EFIS to occupy the entire screen without system border / menu
  screenFullSize: True

  # Screen background color RGB
  screenColor: (0,0,0)

  # If left out the first defined screen will be default
  defaultScreen: SixPackNew

menu:
  menus:
  # The button configuration is ['button text', 'action', 'argument']
  # Currently limited to 6 buttons.  Comment out this entire section to hide menus if you are using real buttons.
      PFDMenu:
          - ['Hide', 'activate menu', 'ShowMenu']
          - ['Back', 'Show Previous Screen','']
          - ['Next', 'Show Next Screen','']
          - ['EMS', 'Show Screen','EMS']
          - ['Units', 'Set Instrument Units', 'OAT,OILT1,Temperature:Toggle']
          - ['Basic', 'activate menu','BasicMenu']
      BasicMenu:
          - ['Hide', 'activate menu', 'ShowMenu2']
          - ['PFD', 'Show Screen','PFD']
          - ['EPFD', 'Show Screen','EPFD']
          - ['EMS', 'Show Screen','EMS']
          - ['Six', 'Show Screen','SixPack']
          - ['Main', 'activate menu','PFDMenu']
      ShowMenu:
          - ['Show', 'activate menu','PFDMenu']
      ShowMenu2:
          - ['Show', 'activate menu','BasicMenu']
  start_menu: ShowMenu
#  show_time: 3  # hides the menu after 3 seconds.  However cannot show again.  Don't use.  Here for reference only.
  number_of_buttons: 6
  buttons_spacing: 120
  left_margin: 50
  top_margin: 420

# The keybindings are used to attach keystrokes to actions.  The key can be
# a string that represents a key Sequence.  See the documentation for more
# information about key sequences and actions.
keybindings:
  - key: A
    action: Show Previous Screen

  - key: S
    action: Show Next Screen

  - key: P
    action: Show Screen
    args: PFD

  - key: M
    action: Set Airspeed Mode

  - key: Q
    action: Set Value
    args: BTN6, True
    direction: DN
  - key: Q
    action: Set Value
    args: BTN6, False
    direction: UP
  - key: U
    action: Set Instrument Units
    args: OAT,OILT1,Temperature:Toggle

  - key: F1
    action: Activate Menu Item
    args: 1
  - key: F2
    action: Activate Menu Item
    args: 2
  - key: F3
    action: Activate Menu Item
    args: 3
  - key: F4
    action: Activate Menu Item
    args: 4
  - key: F5
    action: Activate Menu Item
    args: 5
  - key: F6
    action: Activate Menu Item
    args: 6

  - key: ']'
    action: Change Value
    args: BARO,0.01
  - key: '['
    action: Change Value
    args: BARO,-0.01

# Data bindings tie actions to values in teh database
# key is the database key and should match the FIX Gateway key
databindings:
  - key: BTN1
    condition: True
    action: Activate Menu Item
    args: 1
  - key: BTN2
    condition: True
    action: Activate Menu Item
    args: 2
  - key: BTN3
    condition: True
    action: Activate Menu Item
    args: 3
  - key: BTN4
    condition: True
    action: Activate Menu Item
    args: 4
  - key: BTN5
    condition: True
    action: Activate Menu Item
    args: 5
  - key: BTN6
    condition: True
    action: Activate Menu Item
    args: 6
  - key: ENC1
    action: Menu Encoder
    args: <VALUE>   # This sends the data value to the action
  - key: OILP1
    condition: < 25
    action: Show Screen
    args: EMS


# This section defines FIX IDs that we'll write out to the
# FIX Gateway server.  Each can be defined as one of three
# methods.  Interval will look at the time out lifetime (TOL)
# of the point and send the data at half that interval.
# OnChange will send when the value is changed and Both will
# do both.
outputs:
  #TAS = Interval
  BARO: Interval
  BTN16: OnChange


# Screen definitions describe the screens that will be loaded
# and ready for use.  Each section should start with "Screen."
# followed by the name.  The only required configuration is
# module, which is the module that will be loaded to render
# the screen

screens:
  EPFD:
    module: pyefis.screens.epfd
    title: Primary Flight Display
    dbpath: /home/phil/.makerplane/data/CIFP/FAACIFP18
    indexpath: /home/phil/.makerplane/data/CIFP/index.bin
    check_engine: [MAP1, TACH1, OILP1, OILT1, FUELQT, FUELF1, CHTMAX1, EGTAVG1]
    update_period: .1

  PFD:
    module: pyefis.screens.pfd
    title: Primary Flight Display
    dbpath: /home/phil/.makerplane/data/CIFP/FAACIFP18
    indexpath: /home/phil/.makerplane/data/CIFP/index.bin
    update_period: .1

  EMS:
    module: pyefis.screens.ems_sm
    title: Engine Management

  EMSNew:
    module: pyefis.screens.screenbuilder
    title: Engine Management
    layout:
      type: grid #Splits the screen into evenly sized grids where each grid can contain a single insturment
      rows: 800
      columns: 640
    instruments:
      -
        type: arc_gauge
        row: 1
        column: 1



  SixPack:
    module: pyefis.screens.sixpack
    title: Standard Instrument Panel

  SixPackNew:
    module: pyefis.screens.screenbuilder
    title: Standard Instrument Panel
    layout:
      type: grid #Splits the screen into evenly sized grids where each grid can contain a single insturment
      rows: 2
      columns: 3
      margin:
        top: 10
        left: 10
        right: 10
        bottom: 10
    instruments:
      # Add mapping feature
      # Some instruments need multiple inputs, how would one know what values/mapping is needed?
      # span
      #  rows: 2
      #  columns: 3
      -
        type: airspeed_dial
        row: 1
        column: 1
      - type: atitude_indicator
        row: 1
        column: 2
      -
        type: altimeter_dial
        row: 1
        column: 3
      -
        type: turn_coordinator
        row: 2
        column: 1
      - 
        type: horizontal_situation_indicator
        row: 2             # Row where this grid starts vertical, 1 is top
        column: 2          # Column where this grid starts horizontal, 1 is left
                           # Span is not yet implemented
        #span:             # Defines if this grid should span multiple columns or rows making it larger
          #rows: 2         # This grid will occupuy row 2 and 3, 2 rows
          #columns: 2      # This grid will occupy columns 2 and 3, 2 columns
        move:              # Everything maintains aspect ratio of the grid you defined, 
                           # with row, column and span but you can make things smaller by percentages
                           # The default is for the object to occupy the whole space
          shrink: 21       # This will reduce the size by 10 percent
                           # When shrinking the default is for the object to be centered horizontal and vertically
          justify:         # If you want to move it you can use 'top', 'bottom', 'left' or 'right'
            - bottom       # If you decide to configure top and bottom or right and left
                           # Only one of the mutually exclusive options will be used
                           # While this might seem limiting, keep in mind that you can make a high number of initial grids
                           # Then use span along with shrink and justify to get items precisely placed.
                           # Hopefully one day all the widgets will be updated to scale fonts and such based on the size of the space they occupy
                           # This would make it very simple to resize, just change the size of the window and all items will be proportionally 
                           # moved and sized to fit. If you go wider gauges might have more space between them horizontally
                           # However, the screen would still be usable without having to change any other setting.
        options:
          gsi_enabled: true
          cdi_enabled: true
      -
        type: heading_display
        column: 2
        row: 2
        move:
          shrink: 80
          justify:
            - top

      -
        type: vsi_dial
        row: 2
        column: 3
  PFDSM:
    module: pyefis.screens.pfd_sm
    title: PFD Small

  #Test:
  #  module: pyefis.screens.test
  #  title: Test Screen

# Hooks are user defined modules that are loaded at specific points
# in the programs execution.  Right now their is only one place and
# it is right after all of the initialization and just before the
# main window and default screen are shown.  We'll add more as the
# need arises.
hooks:
  # Keys:
  #   module: user.hooks.keys
  # Composite:
  #   module: user.hooks.composite


# Logging configuration - See Python logging.config module documenation
# Logging configuration - See Python logging.config module documenation
logging:
  version: 1
  disable_existing_loggers: False
  loggers:
    '':
      # messages with levels below the one given will not be logged
      #level: DEBUG
      level: INFO
      #level: WARNING
      #level: ERROR
      #level: CRITICAL

      handlers: [stderr, file]
      propagate: True

  formatters:
    standard:
      format: "%(levelname)s:%(asctime)s:%(name)s - %(message)s"
      datefmt: "%Y%m%d-%H:%M:%S"
      class: logging.Formatter

  handlers:
    stderr:
      class: logging.StreamHandler
      formatter: standard
      stream: ext://sys.stderr

    file:
      class: logging.FileHandler
      formatter: standard
      filename: fixgw.log
      mode: w
      #mode: a

    syslog:
      class: logging.handlers.SysLogHandler
      formatter: standard
